name: Build and Push vLLM GPT-OSS Docker Image

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # 1️⃣ Free up space for large CUDA build
      - name: Free up space
        run: |
          sudo rm -rf /usr/share/dotnet /usr/local/lib/android /opt/ghc /opt/hostedtoolcache 
          df -h

      # 2️⃣ Clone the vLLM repo
      - name: Clone vLLM repository
        run: |
          git clone https://github.com/zyongye/vllm.git
          cd vllm
          git checkout 8260948cdc379d13bf4b80d3172a03d21a983e05
          cd ..
      - name: Show repo contents
        run: ls -R

      # 3️⃣ Copy your custom Dockerfile into the repo
      #    Make sure you have added Dockerfile_gpt-oss to *this* repo so Actions can see it
      - name: Copy custom Dockerfile
        run: cp Dockerfile_gpt-oss vllm/

      # 4️⃣ Set up Docker Buildx for multi-platform builds
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      # 5️⃣ Log in to Docker Hub
      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      # 6️⃣ Build and Push Docker Image
      - name: Build and Push vLLM GPT-OSS Image
        uses: docker/build-push-action@v5
        with:
          context: vllm
          file: vllm/Dockerfile_gpt-oss
          push: true
          build-args: |
            RUN_WHEEL_CHECK=false
            max_jobs=64
            nvcc_threads=2
          target: vllm_gpt-oss
          tags: nhuytan/vllm-gptoss:0.10.2
